import { defineConfig } from 'tsup';

export default defineConfig({
  entry: {
    'lib/ticketCommentAttachments': 'lib/ticketCommentAttachments.ts',
    'lib/ticketCommentAttachmentToken': 'lib/ticketCommentAttachmentToken.ts',
    'index': 'index.ts',
    'types/index': 'types/index.ts',
    'core/logger': 'core/logger.ts',
    'core/secretProvider': 'core/secretProvider.ts',
    'core/deploymentProfile': 'core/deploymentProfile.ts',
    'db/index': 'db/index.ts',
    'db/admin': 'db/admin.ts',
    'db/connection': 'db/connection.ts',
    'db/tenant': 'db/tenant.ts',
    'events/publisher': 'events/publisher.ts',
    'utils/encryption': 'utils/encryption.ts',
    'utils/retryUtils': 'utils/retryUtils.ts',
    'services/email/microsoftEmailProviderConfig': 'services/email/microsoftEmailProviderConfig.ts',
    'services/email/providers/MicrosoftGraphAdapter': 'services/email/providers/MicrosoftGraphAdapter.ts',
    'workflow/index': 'workflow/index.ts',
    'workflow/runtime/index': 'workflow/runtime/index.ts',
    'workflow/persistence/index': 'workflow/persistence/index.ts',
    'workflow/streams/index': 'workflow/streams/index.ts',
    'workflow/streams/eventBusSchema': 'workflow/streams/eventBusSchema.ts',
    'workflow/streams/redisStreamClient': 'workflow/streams/redisStreamClient.ts',
    'workflow/streams/workflowEventPublishHelpers': 'workflow/streams/workflowEventPublishHelpers.ts',
    'workflow/streams/workflowEventSchema': 'workflow/streams/workflowEventSchema.ts',
    'workflow/streams/domainEventBuilders/appointmentEventBuilders': 'workflow/streams/domainEventBuilders/appointmentEventBuilders.ts',
    'workflow/streams/domainEventBuilders/assetEventBuilders': 'workflow/streams/domainEventBuilders/assetEventBuilders.ts',
    'workflow/streams/domainEventBuilders/capacityThresholdEventBuilders': 'workflow/streams/domainEventBuilders/capacityThresholdEventBuilders.ts',
    'workflow/streams/domainEventBuilders/clientEventBuilders': 'workflow/streams/domainEventBuilders/clientEventBuilders.ts',
    'workflow/streams/domainEventBuilders/contactEventBuilders': 'workflow/streams/domainEventBuilders/contactEventBuilders.ts',
    'workflow/streams/domainEventBuilders/contractEventBuilders': 'workflow/streams/domainEventBuilders/contractEventBuilders.ts',
    'workflow/streams/domainEventBuilders/creditNoteEventBuilders': 'workflow/streams/domainEventBuilders/creditNoteEventBuilders.ts',
    'workflow/streams/domainEventBuilders/crmInteractionNoteEventBuilders': 'workflow/streams/domainEventBuilders/crmInteractionNoteEventBuilders.ts',
    'workflow/streams/domainEventBuilders/documentAssociationEventBuilders': 'workflow/streams/domainEventBuilders/documentAssociationEventBuilders.ts',
    'workflow/streams/domainEventBuilders/documentGeneratedEventBuilders': 'workflow/streams/domainEventBuilders/documentGeneratedEventBuilders.ts',
    'workflow/streams/domainEventBuilders/documentStorageEventBuilders': 'workflow/streams/domainEventBuilders/documentStorageEventBuilders.ts',
    'workflow/streams/domainEventBuilders/emailFeedbackEventBuilders': 'workflow/streams/domainEventBuilders/emailFeedbackEventBuilders.ts',
    'workflow/streams/domainEventBuilders/externalMappingEventBuilders': 'workflow/streams/domainEventBuilders/externalMappingEventBuilders.ts',
    'workflow/streams/domainEventBuilders/inboundEmailReplyEventBuilders': 'workflow/streams/domainEventBuilders/inboundEmailReplyEventBuilders.ts',
    'workflow/streams/domainEventBuilders/integrationConnectionEventBuilders': 'workflow/streams/domainEventBuilders/integrationConnectionEventBuilders.ts',
    'workflow/streams/domainEventBuilders/integrationSyncEventBuilders': 'workflow/streams/domainEventBuilders/integrationSyncEventBuilders.ts',
    'workflow/streams/domainEventBuilders/integrationTokenEventBuilders': 'workflow/streams/domainEventBuilders/integrationTokenEventBuilders.ts',
    'workflow/streams/domainEventBuilders/integrationWebhookEventBuilders': 'workflow/streams/domainEventBuilders/integrationWebhookEventBuilders.ts',
    'workflow/streams/domainEventBuilders/mediaEventBuilders': 'workflow/streams/domainEventBuilders/mediaEventBuilders.ts',
    'workflow/streams/domainEventBuilders/notificationEventBuilders': 'workflow/streams/domainEventBuilders/notificationEventBuilders.ts',
    'workflow/streams/domainEventBuilders/projectLifecycleEventBuilders': 'workflow/streams/domainEventBuilders/projectLifecycleEventBuilders.ts',
    'workflow/streams/domainEventBuilders/projectTaskEventBuilders': 'workflow/streams/domainEventBuilders/projectTaskEventBuilders.ts',
    'workflow/streams/domainEventBuilders/recurringBillingRunEventBuilders': 'workflow/streams/domainEventBuilders/recurringBillingRunEventBuilders.ts',
    'workflow/streams/domainEventBuilders/scheduleBlockEventBuilders': 'workflow/streams/domainEventBuilders/scheduleBlockEventBuilders.ts',
    'workflow/streams/domainEventBuilders/surveyEventBuilders': 'workflow/streams/domainEventBuilders/surveyEventBuilders.ts',
    'workflow/streams/domainEventBuilders/tagEventBuilders': 'workflow/streams/domainEventBuilders/tagEventBuilders.ts',
    'workflow/streams/domainEventBuilders/technicianDispatchEventBuilders': 'workflow/streams/domainEventBuilders/technicianDispatchEventBuilders.ts',
    'workflow/secrets/index': 'workflow/secrets/index.ts',
    'workflow/workers/index': 'workflow/workers/index.ts',
    'workflow/services/index': 'workflow/services/index.ts',
    'extension-utils/index': 'extension-utils/index.ts',
    'models/clientModel': 'models/clientModel.ts',
    'models/contactModel': 'models/contactModel.ts',
    'models/kbArticleModel': 'models/kbArticleModel.ts',
    'models/scheduleEntry': 'models/scheduleEntry.ts',
    'models/tagModel': 'models/tagModel.ts',
    'models/ticketModel': 'models/ticketModel.ts',
    'models/userModel': 'models/userModel.ts',
    'utils/recurrenceUtils': 'utils/recurrenceUtils.ts',
    'extensions/domain': 'extensions/domain.ts',
    'extensions/installs': 'extensions/installs.ts',
    'extensions/types': 'extensions/types.ts',
    'billingClients/index': 'billingClients/index.ts',
    // packages/jobs runs vitest from its own root, so this resolves through the
    // exports map into dist/ rather than being transpiled from source the way
    // the Next-built consumers are. Without an entry it is "Cannot find
    // package" at test time.
    'billingClients/hourBlockService': 'billingClients/hourBlockService.ts',
    'billingClients/bucketUsageService': 'billingClients/bucketUsageService.ts',
    'billingClients/bucketUsageErrors': 'billingClients/bucketUsageErrors.ts',
    'billingClients/weightedBurn': 'billingClients/weightedBurn.ts',
    'billingClients/drawAdjustments': 'billingClients/drawAdjustments.ts',
    'billingClients/templateClone': 'billingClients/templateClone.ts',
    'lib/ticketActivity/index': 'lib/ticketActivity/index.ts',
    'lib/ticketActivity/types': 'lib/ticketActivity/types.ts',
    'lib/ticketActivity/writeTicketActivity': 'lib/ticketActivity/writeTicketActivity.ts',
    'lib/ticketActivity/readTicketActivity': 'lib/ticketActivity/readTicketActivity.ts',
    'lib/ticketActivity/curatedTicketDiff': 'lib/ticketActivity/curatedTicketDiff.ts',
    'lib/businessHours/businessHoursSegmentation': 'lib/businessHours/businessHoursSegmentation.ts',
  },
  format: ['esm'],
  dts: false,
  bundle: true,
  splitting: true,
  sourcemap: false,
  clean: true,
  outDir: 'dist',
  external: [
    'react',
    'react-dom',
    'knex',
    'pg',
    'redis',
    'winston',
    'winston-daily-rotate-file',
    'uuid',
    'zod',
    'dotenv',
    'axios',
    'jsonata',
    'turndown',
    'node-vault',
    'googleapis',
    'google-auth-library',
    '@js-temporal/polyfill',
    /^@alga-psa\//,
  ],
  noExternal: [
    /^@shared\//,
  ],
});
